[project]
name = "devtrace"
version = "0.1.1"
dependencies = [
    "click",
    "colorama",
    "rich",
    "python-slugify",
    "Pygments",
    "markdown-it-py",
    "requests",
]

[project.scripts]
devtrace = "devtrace.cli:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["devtrace"]